#!/usr/bin/env bash
# PreToolUse(Write|Edit) hook — block writes to generated / build / dependency
# artifacts and to lock files. Deterministic guardrail: it stops the agent from
# wasting a turn editing output instead of source, and points it at the source.
#
# Project-agnostic. It recognises a protected target four ways, so it needs no
# per-project path list:
#   1. the path lies in a generated / build / dependency directory;
#   2. the basename is a known package-manager lock file;
#   3. the basename matches a generated-artifact naming convention
#      (*.gen.*, *.generated.*, protobuf stubs, minified bundles);
#   4. an existing file's header carries the universal codegen marker
#      ("DO NOT EDIT" / "@generated").
#
# A blocked write is announced to the user via a JSON `systemMessage`; the
# matching `permissionDecisionReason` is fed back to the agent.
set -uo pipefail

command -v jq >/dev/null 2>&1 || exit 0

FILE_PATH=$(jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
[ -n "$FILE_PATH" ] || exit 0

# Emit a deny decision as JSON: the user sees a persistent announcement, the
# agent gets an actionable reason. jq is guaranteed present (checked above).
block() {
  jq -n --arg r "$1" \
    '{systemMessage: ("🪝 Neural Factory · protect-paths hook blocked a write — " + $r),
      hookSpecificOutput: {hookEventName: "PreToolUse",
                           permissionDecision: "deny",
                           permissionDecisionReason: $r}}'
  exit 0
}

BASE=$(basename "$FILE_PATH")

# 1. Generated / build / dependency directories — never hand-edited.
for seg in node_modules .next .nuxt .svelte-kit .astro .output .angular \
           .turbo .parcel-cache .cache dist build out target \
           __pycache__ .venv venv .pytest_cache .mypy_cache .ruff_cache \
           coverage .gradle Pods; do
  case "/$FILE_PATH/" in
    */"$seg"/*)
      block "'$FILE_PATH': '$seg/' is generated / build / dependency output, not source. Edit the source that produces it instead."
      ;;
  esac
done

# 2. Lock files — regenerated by the package manager, never hand-edited.
case "$BASE" in
  package-lock.json|pnpm-lock.yaml|yarn.lock|bun.lock|bun.lockb|\
  poetry.lock|uv.lock|Pipfile.lock|Cargo.lock|composer.lock|Gemfile.lock|\
  go.sum|packages.lock.json)
    block "'$BASE': lock files are regenerated by the package manager. Change the manifest (package.json / pyproject.toml / ...) and re-run install instead."
    ;;
esac

# 3. Generated-artifact naming conventions + minified / bundled assets.
case "$BASE" in
  *.gen.*|*.generated.*|\
  *_pb2.py|*_pb2.pyi|*_pb2_grpc.py|*.pb.go|*_pb.js|*_pb.ts|\
  *.min.js|*.min.css|*.bundle.js)
    block "'$BASE': matches a generated / build-artifact naming convention. Edit the source schema / codegen input instead."
    ;;
esac

# 4. Universal codegen marker in an existing file's header — catches generated
# output wherever it lives and however it is named (route trees, ORM stubs,
# API clients, ...). Restricted to the unambiguous machine markers so files
# that merely *mention* generation in prose are not blocked.
if [ -f "$FILE_PATH" ]; then
  if head -n 15 "$FILE_PATH" 2>/dev/null \
     | grep -qE 'DO NOT EDIT|@generated'; then
    block "'$FILE_PATH': its header marks it as generated ('DO NOT EDIT' / '@generated'). Edit the source or codegen input that produces it instead."
  fi
fi

exit 0
